### ISSUE TITLE
Unexpected removal of line breaks in code blocks

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/docs-build#59]
Some of the code blocks in the Archivematica documentation are of directory structures, where maintaining line breaks and indentation are important. In docs.dev, line breaks in examples were removed, causing 
```
/archivematica_sip_examplerefid
  /logs
  /metadata
    archivesspaceids.csv
    rights.csv
  /objects
    examplerefid_001.tif
    examplerefid_002.tif
    examplerefid_003.tif
    examplerefid.pdf
    /access
      examplerefid.pdf
    /service
      examplerefid_001.tif
      examplerefid_002.tif
      examplerefid_003.tif
```
to look like
```
/archivematica_sip_examplerefid /logs /metadata archivesspaceids.csv rights.csv /objects examplerefid_001.tif examplerefid_002.tif examplerefid_003.tif examplerefid.pdf /access examplerefid.pdf /service examplerefid_001.tif examplerefid_002.tif examplerefid_003.tif 
```
The former is preferred--is it possible to revert this change?

**Comment by kemartin2015** [comment]
@bonniegee Sorry about that. It will display correctly when we merge the homepage redesign changes into the development branch. I added new css classes so that inline code would match the code blocks. I applied these new classes to the archivematica repo prematurely so I wouldn't have to go back later and make the changes. It can be reverted if need be.

**Comment by bonniegee** [comment]
Thanks for the explanation of what's going on, @kemartin2015 ! Since this will be fixed with the next update, I'm okay with leaving it.
